version: '3'

services:
  php:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 7001:80
  db:
    image: mysql:latest
    container_name: lamp_dokcer_mysql
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: lamp_docker_phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password